# Generated by Django 5.1 on 2024-10-14 02:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesForTranslateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, unique=True, verbose_name='Language code')),
                ('name_of_language', models.CharField(max_length=50, null=True, unique=True, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language for video translation',
                'verbose_name_plural': 'Languages for video translation',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Text')),
                ('name', models.CharField(max_length=100, verbose_name='Title name')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='ChangeEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email2', models.CharField(blank=True, max_length=100, null=True, verbose_name='New email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('videos_with_subs', models.FileField(blank=True, null=True, upload_to='videos_with_subs/', verbose_name='Video with subtitles')),
                ('name_of_video', models.CharField(blank=True, max_length=50, null=True, verbose_name='Video title')),
                ('video_size', models.FloatField(blank=True, null=True, verbose_name='Video size in MB')),
                ('make_audio_record', models.BooleanField(default=False, null=True, verbose_name='Is audio translation needed?')),
                ('rendering_progress', models.IntegerField(blank=True, null=True, verbose_name='Rendering progress')),
                ('whisper_progress', models.IntegerField(blank=True, null=True, verbose_name='Transcription progress')),
                ('translate_progress', models.IntegerField(blank=True, null=True, verbose_name='Translation progress')),
                ('voiceover_progress', models.IntegerField(blank=True, null=True, verbose_name='Voiceover progress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User video',
                'verbose_name_plural': 'User videos',
            },
        ),
    ]
