# Generated by Django 5.1 on 2024-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='make_audio_record',
            field=models.BooleanField(default=False, null=True, verbose_name='Нужно ли сделать аудио перевод'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='name_of_video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='videos_with_subs',
            field=models.FileField(blank=True, null=True, upload_to='videos_with_subs/', verbose_name='Видео с субтитрами'),
        ),
    ]
