# Generated by Django 5.1 on 2024-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='rendering_progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс рендеринга'),
        ),
        migrations.AddField(
            model_name='uservideos',
            name='whisper_progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс транскрипции'),
        ),
    ]
