# Generated by Django 4.2.5 on 2023-09-30 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app_auto_subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='name_of_video',
            field=models.CharField(max_length=50, null=True, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='videos_with_subs',
            field=models.FileField(null=True, upload_to='videos_with_subs/%Y/%m/%d/', verbose_name='Видео с субтитрами'),
        ),
    ]
