# Generated by Django 4.2.5 on 2023-10-01 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0002_uservideos_name_of_video_alter_uservideos_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideos',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео'),
        ),
    ]
