# Generated by Django 5.1 on 2024-09-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0002_uservideos_rendering_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='translate_progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс перевода'),
        ),
        migrations.AddField(
            model_name='uservideos',
            name='voiceover_progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс озвучки'),
        ),
    ]
