# Generated by Django 5.1 on 2024-08-27 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0002_uservideos_make_audio_record_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpansionForUser',
            new_name='ChangeEmailModel',
        ),
    ]
