# Generated by Django 5.1 on 2024-08-28 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0003_rename_expansionforuser_changeemailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideos',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео'),
        ),
    ]
