# Generated by Django 5.1 on 2024-09-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0004_uservideos_do_voiceover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideos',
            name='do_voiceover',
        ),
    ]
