# Generated by Django 4.2.5 on 2023-10-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0004_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
