# Generated by Django 5.1 on 2024-10-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0005_remove_uservideos_do_voiceover'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='video_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
