# Generated by Django 4.2.5 on 2023-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0005_title_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesForTranslateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовоки'},
        ),
        migrations.AlterModelOptions(
            name='uservideos',
            options={'verbose_name': 'Пользовательское видео', 'verbose_name_plural': 'Пользовательские видео'},
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название заголовка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='uservideos',
            name='videos_with_subs',
            field=models.FileField(null=True, upload_to='videos_with_subs/', verbose_name='Видео с субтитрами'),
        ),
    ]
