# Generated by Django 4.2.5 on 2023-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0006_languagesfortranslatevideo_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagesfortranslatevideo',
            options={'verbose_name': 'Язык для перевода видео', 'verbose_name_plural': 'Языки для перевода видео'},
        ),
        migrations.AlterField(
            model_name='languagesfortranslatevideo',
            name='language',
            field=models.CharField(max_length=50, unique=True, verbose_name='Язык'),
        ),
    ]
