# Generated by Django 4.2.5 on 2023-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_auto_subs', '0007_alter_languagesfortranslatevideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesfortranslatevideo',
            name='name_of_language',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='languagesfortranslatevideo',
            name='language',
            field=models.CharField(max_length=50, unique=True, verbose_name='Язык в символах'),
        ),
    ]
