FROM python:3.11.3-bullseye

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y ffmpeg libpng-dev libjpeg-dev \
    libtiff-dev libmagickwand-dev imagemagick \
    libmagick++-dev vim \
    && apt-get install libpq-dev


WORKDIR /subs

COPY . /subs/

# RUN apt-get install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
# RUN usermod -a -G render,video $LOGNAME
# RUN wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/noble/amdgpu-install_6.2.60200-1_all.deb
# RUN add-apt-repository -y -s deb http://security.ubuntu.com/ubuntu jammy main universe
# RUN aptget install ./amdgpu-install_6.2.60200-1_all.deb
# RUN apt-get update
# RUN apt-get install amdgpu-dkms rocm



RUN pip install --upgrade pip
RUN pip install -r req.txt

COPY wait-for-postgres.sh /wait-for-postgres.sh
RUN chmod +x /wait-for-postgres.sh


CMD /wait-for-postgres.sh \
    && python3 ./proj/manage.py migrate \
    && python3 ./proj/manage.py makemigrations \
    && python3 ./proj/manage.py migrate \
    && python3 ./proj/manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='root').exists() or User.objects.create_superuser('root', 'root@root.ru', 'root')" \
    && python3 ./proj/manage.py loaddata /subs/initialize_db.json \
    && python3 ./proj/manage.py runserver 0.0.0.0:8000


